config/routes.rb
Rails.application.routes.draw do

  get 'welcome/home'
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"
  get 'users/:user_id/courses', to: "users#courses", as: "user_courses"
  get 'courses/least_popular', to: "courses#least_popular", as: "least_popular_courses"

  resources :instructors
  resources :courses do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :profile
  end

   root 'welcome#home'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :courses, through: :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @profile = @user.try(:profile)
    @courses = @user.try(:profile).try(:courses)
    @reviews = @user.reviews
  end

  def new
    @user = User.find_by(id: params[:user_id])
    @profile = Profile.new
  end

  def create
    @user = User.find_by(id: params[:user_id])
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to user_profile_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find_by(id: params[:user_id])
    @profile = @user.profile
    @profile.update(profile_params)
    if @profile.save
      redirect_to user_profile_path
    else
      render "edit"
    end
  end




  private
  def profile_params
    params.require(:profile).permit(:user_id, :username, :courses_attributes => [
          :user_id,
          :title,
          :department,
          :course_number,
          :description
        ]
      )
  end

  def authorize
    unless current_user.try(:admin?) || current_user.id == params[:id] || current_user.id == params[:user_id].to_i
      raise params.inspect
      flash[:error] = "You are not authorized to view this page."
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<% if @profile.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
            <% @profile.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @profile, url: user_profile_path(current_user) do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.label :username %><br>
    <%= f.text_field :username %>

    <%= f.submit class: "btn btn-outline-dark" %>

<% end %>

app/views/profiles/edit.html.erb
<h2>Edit your profile</h2>
<%= render partial: "form", locals: { user: @user, profile: @profile} %>

app/views/profiles/new.html.erb
<h2>New Profile</h2>
<%= render partial: "form", locals: { user: @user, profile: @profile} %>

app/views/profiles/show.html.erb
<% if !@user.try(:profile) %>
  You have not set up a user profile
  <br><br>
  <%= link_to "Create profile", new_user_profile_path, class: "btn btn-outline-dark" %>
<% else %>
  <h2><%= @profile.username.capitalize %>'s Profile</h2>
  <p>Email: <%= @user.email %></p>

  <h3>Your Courses</h3>
  <ol>
    <% @courses.each do |course| %>
      <li><h4><%= link_to course.full_title, course_path(course) %></h4>
        <ul>
          <li><%= link_to course.instructor_name, instructor_path(course.instructor) %></li>
        </ul>
          <br>
          <small class="text-muted">Last updated: <%= course.updated_at.strftime("%m/%d/%Y") %></small>
    <% end %></li>
  </ol>

  <h3>Reviews on your Courses</h3>
  <ol>
    <% @reviews.each do |review| %>
      <li><h4>Review for <%= link_to review.course.full_title, course_path(review.course) %></h4>
          <small class="text-muted">
            By:
            <% if review.user == review.course.user %>
              You
            <% else %>
                <%= review.user.email %> (<%= review.user.profile.username %>)
            <% end %>
            | Last updated: <%= review.updated_at.strftime("%m/%d/%Y") %>
          </small>
    <% end %></li>
  </ol>

  <%= link_to "Edit your profile", edit_user_profile_path, class: "btn btn-outline-dark" %>
<% end %>