config/routes.rb
Rails.application.routes.draw do

  get 'welcome/home'
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"
  get 'users/:user_id/courses', to: "users#courses", as: "user_courses"
  get 'courses/least_popular', to: "courses#least_popular", as: "least_popular_courses"

  resources :instructors
  resources :courses do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :profile
  end

   root 'welcome#home'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :courses
  accepts_nested_attributes_for :courses
  validates_presence_of :first_name, :second_name

  def full_name
    self.first_name + " " + self.second_name
  end

  def instructor?
    self.instructor.first_name.nil?
  end

  def overall_rating
    (self.reviews.collect{|r| r.instructor_quality}.inject(0){|sum,x| sum + x }/self.reviews.count.to_f).round(2)
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :require_login, only: [:new, :create]

def index
  @instructors = Instructor.all
end

def new
  @instructors = Instructor.all
  @instructor = Instructor.new
  @instructor.courses.build()
end

def create
  @instructor = Instructor.new(instructor_params)
  if @instructor.save
    redirect_to @instructor
  else
    render "new"
  end
end

def show
  @instructor = Instructor.find_by(id: params[:id])
  @courses = @instructor.courses
end

def edit
  @instructor = Instructor.find_by(id: params[:id])
  @instructor.courses.build()
end

def update
  @instructor = Instructor.find_by(id: params[:id])
  @instructor.update(instructor_params)
  if @instructor.save
    redirect_to instructor_path(@instructor)
  else
    render "edit"
  end
end

def new_course
  @instructor = Instructor.find_by(id: params[:id])
  @course = @instructor.courses.build
end

def destroy
  @instructor = Instructor.find_by(id: params[:id])
  @instructor.destroy
  redirect_to root_path
end

private

  def instructor_params
    params.require(:instructor).permit(
      :user_id,
      :first_name,
      :second_name,
      :courses_attributes => [
        :user_id,
        :title,
        :department,
        :course_number,
        :description
      ]
      )
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<% if @instructor.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>
          <ul>
              <% @instructor.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
      </div>
  <% end %>

<%= form_for @instructor do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :second_name, "Last Name" %><br>
  <%= f.text_field :second_name %>
  <br>
  <fieldset>
    <legend>Add Course (optional)</legend>
    <%= f.fields_for :courses, @instructor.courses do |course_fields| %>
    <%= course_fields.hidden_field :user_id, value: current_user.id %>
      <%= course_fields.label :title %><br>
      <%= course_fields.text_field :title %>
      <br>
      <%= course_fields.label :department %><br>
      <%= course_fields.text_field :department%>
      <br>
      <%= course_fields.label :course_number %><br>
      <%= course_fields.text_field :course_number %>
      <br>
      <%= course_fields.label :description %><br>
      <%= course_fields.text_area :description %>
    <% end %>
  </fieldset>

  <%= f.submit %>
<% end %>

app/views/instructors/_instructor_details_for_index.html.erb
<h3>All Instructors</h3>
  <ol>
    <% @instructors.each do |instructor| %>
        <li> <%= link_to instructor.full_name, instructor_path(instructor) %></li>
        <!-- <small><%= last_updated instructor %></small> -->
    <% end %>
  </ol>

app/views/instructors/edit.html.erb
<h2>Edit Instructor</h2>
<%= form_for @instructor do |f| %>
<%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :second_name, "Last Name" %><br>
  <%= f.text_field :second_name %>
  <br>
  <%= f.submit %>
<% end %>

<%= button_to "Delete Instructor", @instructor, :method => :delete, class: "btn btn-outline-danger" if !!@instructor.id && (current_user.try(:admin?) || current_user.id == @instructor.user_id) %>

app/views/instructors/index.html.erb
<%= render partial: "instructors/instructor_details_for_index", locals: {instructors: @instructors} %>

app/views/instructors/new.html.erb
<h2>New Instructor</h2>
<%= render partial: "form", locals: { instructor: @instructor } %>
<%= render partial: "instructors/instructor_details_for_index", locals: {instructors: @instructors} %>

app/views/instructors/new_course.html.erb
<% if @instructor.errors.any? %>
      <div id="error_explanation">
          <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this activity from being saved:</h2>
          <ul>
              <% @instructor.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
      </div>
  <% end %>
<%= form_for @instructor do |f| %>
  <%= f.fields_for :courses, @instructor.courses.build do |course| %>
  <%= course.hidden_field :user_id, value: current_user.id %>
  <h3>New Course for <%= @instructor.full_name%> </h3>
    <%= course.label :title %><br>
    <%= course.text_field :title %>
    <br>
    <%= course.label :department %><br>
    <%= course.text_field :department %>
    <br>
    <%= course.label :course_number %><br>
    <%= course.text_field :course_number %>
    <br>
    <%= course.label :description %><br>
    <%= course.text_area :description %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/instructors/show.html.erb
<h1><%= @instructor.first_name%> <%=@instructor.second_name%></h1>

  <h3>Courses</h3>
    <ol>
      <% @instructor.courses.each do |course| %>
        <li><h3><%= course.department%>-<%=course.title %></h3>
        <p class="card-text"><%= course.description %></p>
          <div class="btn-group">
            <%= button_to "View", course_path(course), method: :get %>
          </div>
          <div class="btn-group">
            <%= button_to "Edit", edit_course_path(course), method: :get, class: "btn btn-sm btn-outline-secondary" if edit_option course %>
          </div>
          <small class="text-muted"><%= last_updated course %></small>
      <% end %></li>
      </ol>
      <br>
      <%= button_to "Add a Course", new_instructor_course_path %> <!--was "link_to" -->
      <%= button_to "Edit Instructor", edit_instructor_path, method: :get, class: "btn btn-sm btn-outline-secondary" if edit_option @instructor %>
      <br>