config/routes.rb
Rails.application.routes.draw do

  get 'welcome/home'
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"
  get 'users/:user_id/courses', to: "users#courses", as: "user_courses"
  get 'courses/least_popular', to: "courses#least_popular", as: "least_popular_courses"

  resources :instructors
  resources :courses do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :profile
  end

   root 'welcome#home'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @review = @course.reviews
  end

  def new
    @instructor = Instructor.new
    @instructor.courses.build()
    @instructors = Instructor.all
    #flash.now[:alert] = "You must create a course through an instructor"
    #redirect_to new_instructor_path
  end

  #def create
  #  @course = Course.new(course_params)
  #  binding.pry
  #  if @course.save
  #    redirect_to course_path(@course)
  #  else
  #    flash.now[:alert] = "You must enter a name and description of the course"
  #    render "new"
  #  end
  #end

  def edit
    @course = Course.find_by(id: params[:id])
    @course.build_instructor() unless @course.instructor
  end

  def update
    @course = Course.find_by(id: params[:id])
    @course.update(course_params)
    if @course.save
      redirect_to course_path(@course)
    else
      render "edit"
    end
  end

  def destroy
    @course = Course.find_by(id: params[:id])
    @course.destroy
    redirect_to root_path
  end

  def least_popular
    @least_popular = Course.least_popular
  end

  private

  def course_params
    params.require(:course).permit(:id,
      :user_id,
      :title,
      :description,
      :department,
      :course_number,
      instructor_attributes: [
        :id,
        :user_id,
        :first_name,
        :second_name
      ]
    )
  end

  def authorize
    unless current_user.try(:admin?) || current_user.id == Course.find_by(id: params[:id]).user_id
      flash[:error] = "You are not authorized to view this page."
      redirect_back(fallback_location: root_path)
    end
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
  def edit_option(obj)
    obj.user_id == current_user.try(:id)
  end
end

app/views/courses/_course_details_for_index.html.erb
<ol>
  <% @courses.each do |course| %>
    <li><h3><%= course.full_title%></h3>
      <h5>Instructor: <%= course.instructor_name %></h5>
      <p class="card-text"><%= course.description %></p>
        <div class="btn-group">
          <%= button_to "View", course_path(course), method: :get, class: "btn btn-sm btn-outline-secondary" unless params[:action] == 'show' && params[:controller] == 'courses' %>
          <%= button_to "Edit", edit_course_path(course), method: :get, class: "btn btn-sm btn-outline-secondary" if edit_option course %>
        </div>
        <br>
        <small class="text-muted"><%= last_updated course %></small>
  <% end %></li>
</ol>

app/views/courses/_form.html.erb
<%= form_for course do |f| %>
  <% if course.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(course.errors.count, "error") %> prohibited this activity from being saved:</h2>
            <ul>
                <% course.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
      <br>
      <%= f.label :Department %><br>
      <%= f.text_field :department, placeholder: "4 letter abbreviation" %>
      <br>
      <%= f.label :course_number %><br>
      <%= f.text_field :course_number, placeholder: "must be 3 numbers" %>
      <br>
      <%= f.label :Description %><br>
      <%= f.text_area :description %>
    <br>
    <%= f.submit %>
<% end %>
<br>
<%= button_to "Delete Course", course, :method => :delete, class: "btn btn-outline-danger" if !!course.id && (current_user.try(:admin?) || current_user.id == course.user_id) %>

app/views/courses/edit.html.erb
<h3>Edit Course</h3>
  <%= render partial: "form", locals: { course: @course} %>

app/views/courses/index.html.erb
  <h1>Courses</h1>
    <%= render partial: "courses/course_details_for_index", locals: {course: @course} %>

app/views/courses/least_popular.html.erb
<h3>Least popular courses:</h3>
<% @least_popular.each do |course| %>
  <%= course.full_title %>
<% end %>

app/views/courses/new.html.erb
<h2>Create a new course</h2>

<h3>Options:</h3>
<ol>
  <li><%= link_to "Create a new course with a new instructor", new_instructor_path(@instructor) %></li>
  <li>Add a course to an existent instructor (see the list below)</li>
</ol>

<%= render partial: "instructors/instructor_details_for_index", locals: {instructors: @instructors} %>

app/views/courses/show.html.erb
<div class="course-header">
  <h1><%= @course.full_title %></h1>
</div>
<h3>Instructor: <%= link_to @course.instructor_name, instructor_path(@course.instructor.id)%></h3>

<p><%= @course.description %></p>
    <%= link_to "Edit course", edit_course_path(@course) if edit_option @course %><br>
    <%= link_to "All courses", courses_path, class: "btn btn-outline-dark" %>

<h3>Reviews</h3>

<%= link_to "Write a review", new_course_review_path(@course)%>

    <p>Overall Ratings</p>
    <ul>
      <li> Average Difficulty: <%= @course.avg_difficulty %></li>
      <li> Instructor Quality: <%= @course.instructor_quality %></li>
      <li> Workload: <%= @course.work_amount %></li>
      <li> Amount Learned: <%= @course.amount_learned %></li>
      <li> Overall Quality: <%= @course.overall_quality %></li>
    </ul>

  <br>

  <% @course.reviews.each do |review| %>
    <div class="review-box card rounded">
      <h4>Ratings</h4>
        <p>Course Difficulty: <%=review.difficulty%> | Instructor Quality: <%=review.instructor_quality%> | Amount Learned: <%=review.amount_learned%></li> | Workload: <%=review.work_amount%></li> | Course Quality: <%=review.course_quality%></p>
      <h4>Comment</h4>
        <p><%= review.comment %></p>
      <p><%= link_to review.user.email, user_profile_path(review.user) %> | <%= last_updated review %></p>
    </div>
    <% if current_user == review.user %>
      <%= link_to "Edit your review", edit_course_review_path(id: review.id, course_id: @course.id) %>
       |
      <%= link_to "Delete your review", course_review_path(@course, review), :method => :delete %>
    <% end %>
    <br><br>
  <% end %>