config/routes.rb
Rails.application.routes.draw do

  get 'welcome/home'
  get 'instructors/:id/new_course', to: "instructors#new_course", as: "new_instructor_course"
  get 'users/:user_id/courses', to: "users#courses", as: "user_courses"
  get 'courses/least_popular', to: "courses#least_popular", as: "least_popular_courses"

  resources :instructors
  resources :courses do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resource :profile
  end

   root 'welcome#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= yield %>
  </body>
  <br>
  <footer>
    <%= link_to "New course", new_course_path %> |
    <%= link_to "See all courses", courses_path %> |
    <%= link_to "New instructor", new_instructor_path %> |
    <%= link_to "See all instructors", instructors_path %> |
    <% if user_signed_in? %>
      <%=  link_to "Your Profile", user_profile_path(current_user) %> |
    <% end %>
    <br>
    <small><%= link_to "Homepage", welcome_home_path %></small>
      |
    <% if user_signed_in? %>
      <small><%= link_to('Logout', destroy_user_session_path, method: :delete) %></small>
    <% else %>
      <small><%= link_to('Login', new_user_session_path)  %> or <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></small>
    <% end %>
    <br>
    <br>
    <% if user_signed_in? %>
      <small>Signed in as <%= current_user.email %></small>
    <% end %>
  </footer>
</html>